version: "3.9"

services:

  nginx:
    container_name: nginx
    build: ./nginx
    image: arches_via_docker/nginx
    env_file:
      - ./.env
    environment:
      - DOMAINS="${DOMAINS}"
      - DEPLOY_HOST="${DEPLOY_HOST}"
      - CERT_PATH="${CERT_PATH}"
      - DJANGO_PORT="${DJANGO_PORT}"
    volumes:
      - nginx-log:/logs/nginx
      - nginx_ssl:/etc/nginx/ssl
      - certbot_certs:/etc/letsencrypt
      - arches_certbot:$CERT_PATH
      - arches-static:/static_root
      - ./html:$NGINX_HTML_PATH
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - arches_net

  certbot:
    container_name: certbot
    build: ./certbot
    image: arches_oc/certbot
    env_file:
      - ./.env
    volumes:
      - certbot_certs:/etc/letsencrypt
      - arches_certbot:$CERT_PATH
    depends_on:
      - nginx

  cron:
    container_name: cron
    build: ./cron
    image: arches_via_docker/cron
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    depends_on:
      - nginx
      - certbot

  arches_db:
    container_name: arches_db
    image: postgis/postgis:14-3.2
    env_file:
      - ./.env
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgis
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology
    restart: always
    volumes:
        - postgres-data:/var/lib/postgresql/data/
        - postgres-log:/var/log/postgresql
        - ./init-unix.sql:/docker-entrypoint-initdb.d/init.sql # to set up the DB template
    ports:
      - '5434:5432'
    networks:
      - arches_net

  arches_elasticsearch:
    container_name: arches_elasticsearch
    image: elasticsearch:8.3.1
    restart: always
    env_file:
      - ./.env
    environment:
      - TZ="${TZ}"
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms400m -Xmx400m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9202:9200"
      - "9302:9300"
    networks:
      - arches_net

  arches:
    container_name: arches
    image: arches
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: arches/Dockerfile
    environment:
      - DEBUG="${DEBUG}"
      - ARCHES_PROJECT=${ARCHES_PROJECT}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "5432:5432"
      - "8983:8983"
      - 8004:8000
      - 5678:5678
    depends_on:
      - arches_db
      - arches_elasticsearch
    command:
      - run_arches
      - run_webpack
    expose:
      - 8004:8000
      - 8021:8021
    volumes:
      - arches-log:/web_root/logs
      - arches-static:/static_root
      - ../arches_data/:/web_root/arches_data
    networks:
      - arches_net

networks:
  arches_net:
    driver: bridge
    name: arches_net

volumes:
  logs_nginx:
    external: true
  nginx_ssl:
    external: true
  certbot_certs:
    external: true
  arches_certbot:
    external: true
  couchdb-data:
  couchdb-log:
  postgres-data:
  postgres-log:
  elasticsearch-data:
  rabbitmq-logs:
  rabbitmq-data:
  arches-log:
  arches-static:
  nginx-log:
